export const ExecutiveImage: Record<string, string> = {
  "Aidan Gomez": "executives/AidanGomez.png",
  "Alex Wang": "executives/AlexWang.png",
  "Andrew Ng": "executives/AndrewNg.png",
  "Aravind Srinivas": "executives/Aravind.png",
  "Arthur Mensch": "executives/ArthurMensch.png",
  "Arvind Krishna": "executives/ArvindKrishna.png",
  "Brad Lightcap": "executives/BradLightcap.png",
  "C.C. Wei": "executives/C.C.Wei.png",
  "Chris Cox": "executives/ChrisCox.png",
  "Daniela Amodei": "executives/DanielaAmodei.png",
  "Daphne Koller": "executives/DaphneKoller.png",
  "Dario Amodei": "executives/DarioAmodei.png",
  "Dario Gil": "executives/DarioGil.png",
  "Demis Hassabis": "executives/DemisHassabis.png",
  "Fei-Fei Li": "executives/Fei-FeiLi.png",
  "Ilya Sutskever": "executives/IlyaSutskever.png",
  "James Manyika": "executives/JamesManyika.png",
  "Jeff Dean": "executives/JeffDean.png",
  "Jensen Huang": "executives/JensenHuang.png",
  "Jim Keller": "executives/JimKeller.png",
  "Joelle Pineau": "executives/Joelle.png",
  "Kevin Scott": "executives/KevinScott.png",
  "Lisa Su": "executives/LisaSu.png",
  "Mark Zuckerberg": "executives/Mark.png",
  "Mira Murati": "executives/Mira.png",
  "Mustafa Suleyman": "executives/Mustafa.png",
  "Percy Liang": "executives/Percy.png",
  "Richard Socher": "executives/Richard.png",
  "Rumman Chowdhury": "executives/Rumman.png",
  "Sam Altman": "executives/Sam.png",
  "Satya Nadella": "executives/Satya.png",
  "Shivon Zilis": "executives/Shivon.png",
  "Silvio Savarese": "executives/Silvio.png",
  "Sundar Pichai": "executives/Sundar.png",
  "Yann LeCun": "executives/Yann.png",
  "": "avatar.png",
};
